hostname := shell('hostname')

# list recipes
default:
  just --list

# rebuild the system to, e.g., install packages or change configuration
build:
  sudo nixos-rebuild switch --flake .#{{hostname}} --upgrade

update_flake:
  nix flake update --flake .

# update NixOS channels https://nixos.wiki/wiki/Nix_channels
update_channels:
  sudo nix-channel --update

# invoke the garbage collector
# https://nixos.org/guides/nix-pills/11-garbage-collector.html
gc:
  nix-collect-garbage

# full system update
update_system: update_channels update_flake build
